version: "3"
services: 
    project:
        build: .
        ports: 
            - "8080:8080"
        volumes: 
            - ./project:/home/project
            - ./docs:/home/deploy
            - /home/project/docs/node_modules

         
        environment: 
            - CHOKIDAR_USEPOLLING=true