version: "3"
services: 

    frontend:
        image: localhost:5000/raknatee/frontend:1.0.0
        deploy:
          replicas: 3
          placement:
              constraints:
                - "node.hostname==swarm-1"
          labels:
              - "traefik.http.routers.front.rule=PathPrefix(`/`)"
              - "traefik.http.routers.front.entrypoints=web"
              - "traefik.http.services.front.loadbalancer.server.port=80"

    backend:
        image: localhost:5000/raknatee/backend:1.0.0
        deploy:  
          replicas: 3
          placement:
              constraints:
                - "node.hostname==swarm-2"
          labels:
              - "traefik.http.routers.api.rule=PathPrefix(`/api`)" 
              - "traefik.http.routers.api.entrypoints=web"
              - "traefik.http.services.api.loadbalancer.server.port=8000"     


    mongo:
        image: mongo:3.6.22-xenial

        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 1234

        deploy:
            placement:
              constraints:
                - "node.hostname==swarm-2"
        volumes: 
            - mongo-lab-swarm:/data/db
volumes: 
  mongo-lab-swarm: