version: "3"
services: 
   
    api:
        build:
            context: ./webapp
            dockerfile: Dockerfile
  
        ports:
            - "8000:8000"
        volumes:
            - ./webapp/src:/home/src
        env_file:
            - ./secret.env
     

    mongo:
        image: mongo:3.6.22-xenial

        env_file:
            - ./secret.env
        

        volumes: 
            - mongo-sad-lab6:/data/db
volumes: 
  mongo-sad-lab6: